blank_issues_enabled: false
contact_links:
  - name: PatchPilot Discussions
    url: https://github.com/dsj7419/patch-pilot/discussions
    about: Please ask and answer questions here.
  - name: PatchPilot Documentation
    url: https://github.com/dsj7419/patch-pilot/blob/main/README.md
    about: Check the documentation before opening an issue.